### ISSUE TITLE
Title page is offcenter after margin changes.

### ISSUE THREAD

**Issue by ShotgunApe** [jbreitenbucher/exampleis#4]
Margin changes affect how the title page is centered, see commit https://github.com/jbreitenbucher/exampleis/commit/d1c0fb43b5ac2335229622635a56889c418468b7 versus how it looks today: https://github.com/jbreitenbucher/exampleis/commit/246594f41e7e6ee4671a77ce10dbe9c450f51f34.

I have attached images for your convenience:
![image](https://github.com/user-attachments/assets/239a8b82-2527-46dd-b08d-32a23e9dd2f2)

Versus how it looked previously:
![image](https://github.com/user-attachments/assets/869bd850-6175-40ab-990a-e86ea22f1a00)

**Comment by jbreitenbucher** [comment]
How does this work with the other cover image options?

**Comment by ShotgunApe** [comment]
`Scottie`, `wblack` and `woostercopyright` all produce the same text location:

![image](https://github.com/user-attachments/assets/b4988474-85d4-47d6-bb6e-3911a5357587)
![image](https://github.com/user-attachments/assets/417f25c7-b4b2-418f-ae7e-4e22892a4826)
![image](https://github.com/user-attachments/assets/81d43948-9a23-49ce-b7cb-9d9edab06a81)
